name: Website Deployment

on: push

jobs:
    build: 
        runs-on: ubuntu-latest
        name: deploying to surge
        steps:
            - uses: actions/checkout@v2
            - name: Install node.js
              uses: actions/setup-node@v2-beta
              with:
                node-version: 12
      - name: Install Surge
        run: npm install -g surge
      - name: Run surge
        run: surge ./ bootcamp_setup_sherry2610.surge.sh --token ${{ secrets.SURGE_TOKEN }}